import type { Metadata } from "next";
import "./globals.css";
import  { ReactQueryClientProvider } from "@/providers/QueryProvider";
// import ToastProvider from "@/providers/ToastProvider";
import ChatContextProvider from "@/context/ChatContext/ChatContextProvider";
import ToastProvider from "@/providers/ToastProvider";
// const ToastProvider = dynamic(() => import("@/providers/ToastProvider"), {
//   ssr: false,
// });
export const metadata: Metadata = {
  title: "Chat Application",
  description: "Generated by Chat Application",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <ReactQueryClientProvider>
        <body>
          <ToastProvider>
            <ChatContextProvider>{children}</ChatContextProvider>
          </ToastProvider>
        </body>
      </ReactQueryClientProvider>
    </html>
  );
}
